# Generated by Django 5.2.7 on 2025-10-20 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        help_text="Current status of the friendship",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User who sent the friend request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User who received the friend request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "db_table": "friendships",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_user", "status"], name="friendships_from_us_a47fdf_idx"
                    ),
                    models.Index(
                        fields=["to_user", "status"], name="friendships_to_user_607283_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="friendships_status_7dbab4_idx"
                    ),
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
