# Generated by Django 5.2.8 on 2025-11-06 06:40

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxonomicRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("level", models.IntegerField(unique=True)),
                ("plural", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("short_code", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("url", models.URLField(validators=[django.core.validators.URLValidator()])),
                ("api_endpoint", models.URLField(blank=True, null=True)),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("irregular", "Irregular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license", models.TextField(blank=True)),
                ("citation_format", models.TextField(help_text="Template for citations")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower number = higher priority for conflicts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"], name="taxonomy_da_is_acti_7d7de9_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.CharField(help_text="Source dataset version", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("processing", "Processing"),
                            ("validating", "Validating"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_size_mb",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("records_total", models.IntegerField(blank=True, null=True)),
                ("records_imported", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="taxonomy.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawCatalogueOfLife",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("col_id", models.CharField(db_index=True, max_length=50)),
                ("parent_id", models.CharField(blank=True, max_length=50)),
                ("basionym_id", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("rank", models.CharField(max_length=50)),
                ("scientific_name", models.CharField(db_index=True, max_length=300)),
                ("authorship", models.CharField(blank=True, max_length=500)),
                ("kingdom", models.CharField(blank=True, max_length=100)),
                ("phylum", models.CharField(blank=True, max_length=100)),
                ("class_name", models.CharField(blank=True, db_column="class", max_length=100)),
                ("order", models.CharField(blank=True, max_length=100)),
                ("family", models.CharField(blank=True, max_length=100)),
                ("subfamily", models.CharField(blank=True, max_length=100)),
                ("tribe", models.CharField(blank=True, max_length=100)),
                ("subtribe", models.CharField(blank=True, max_length=100)),
                ("genus", models.CharField(blank=True, max_length=100)),
                ("subgenus", models.CharField(blank=True, max_length=100)),
                ("section", models.CharField(blank=True, max_length=100)),
                ("species", models.CharField(blank=True, max_length=100)),
                ("subspecies", models.CharField(blank=True, max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("form", models.CharField(blank=True, max_length=100)),
                ("generic_name", models.CharField(blank=True, max_length=100)),
                ("specific_epithet", models.CharField(blank=True, max_length=100)),
                ("infraspecific_epithet", models.CharField(blank=True, max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("extinct", models.CharField(blank=True, max_length=10)),
                ("environment", models.CharField(blank=True, max_length=100)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processing_errors", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.importjob"
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_raw_catalogue_of_life",
            },
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_taxon_id", models.CharField(db_index=True, max_length=100)),
                ("scientific_name", models.CharField(db_index=True, max_length=300)),
                ("authorship", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("synonym", "Synonym"),
                            ("provisional", "Provisionally Accepted"),
                            ("ambiguous", "Ambiguous Synonym"),
                            ("misapplied", "Misapplied"),
                            ("doubtful", "Doubtful"),
                        ],
                        db_index=True,
                        default="accepted",
                        max_length=30,
                    ),
                ),
                ("kingdom", models.CharField(blank=True, db_index=True, max_length=100)),
                ("phylum", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "class_name",
                    models.CharField(blank=True, db_column="class", db_index=True, max_length=100),
                ),
                ("order", models.CharField(blank=True, db_index=True, max_length=100)),
                ("family", models.CharField(blank=True, db_index=True, max_length=100)),
                ("genus", models.CharField(blank=True, db_index=True, max_length=100)),
                ("species", models.CharField(blank=True, db_index=True, max_length=100)),
                ("subkingdom", models.CharField(blank=True, max_length=100)),
                ("subphylum", models.CharField(blank=True, max_length=100)),
                ("subclass", models.CharField(blank=True, max_length=100)),
                ("suborder", models.CharField(blank=True, max_length=100)),
                ("superfamily", models.CharField(blank=True, max_length=100)),
                ("subfamily", models.CharField(blank=True, max_length=100)),
                ("tribe", models.CharField(blank=True, max_length=100)),
                ("subtribe", models.CharField(blank=True, max_length=100)),
                ("subgenus", models.CharField(blank=True, max_length=100)),
                ("section", models.CharField(blank=True, max_length=100)),
                ("subspecies", models.CharField(blank=True, max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("form", models.CharField(blank=True, max_length=100)),
                ("generic_name", models.CharField(blank=True, db_index=True, max_length=100)),
                ("specific_epithet", models.CharField(blank=True, db_index=True, max_length=100)),
                ("infraspecific_epithet", models.CharField(blank=True, max_length=100)),
                ("extinct", models.BooleanField(blank=True, null=True)),
                (
                    "environment",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "nomenclatural_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("iczn", "ICZN - Zoological"),
                            ("icn", "ICN - Botanical"),
                            ("icnp", "ICNP - Prokaryotes"),
                            ("ictv", "ICTV - Viruses"),
                            ("icnafp", "ICNAFP - Algae, Fungi, Plants"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="Direct link to source record"),
                ),
                ("source_reference", models.TextField(blank=True)),
                (
                    "completeness_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0-1 score of data completeness",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0-1 confidence in accuracy",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_name",
                    models.ForeignKey(
                        blank=True,
                        help_text="For synonyms, points to accepted name",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synonyms",
                        to="taxonomy.taxonomy",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.importjob",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="taxonomy.taxonomy",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="taxonomy.taxonomicrank",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="taxonomy.datasource"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeographicDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("area_code", models.CharField(max_length=20)),
                ("gazetteer", models.CharField(max_length=20)),
                ("area_name", models.CharField(blank=True, max_length=200)),
                (
                    "establishment_means",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("native", "Native"),
                            ("introduced", "Introduced"),
                            ("naturalised", "Naturalised"),
                            ("invasive", "Invasive"),
                            ("managed", "Managed"),
                            ("uncertain", "Uncertain"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "occurrence_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("extinct", "Extinct"),
                            ("doubtful", "Doubtful"),
                        ],
                        default="present",
                        max_length=30,
                    ),
                ),
                ("threat_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="taxonomy.datasource"
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="taxonomy.taxonomy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommonName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("language", models.CharField(db_index=True, max_length=10)),
                ("country", models.CharField(blank=True, db_index=True, max_length=2)),
                ("is_preferred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="taxonomy.datasource"
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_names",
                        to="taxonomy.taxonomy",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["source", "-created_at"], name="taxonomy_im_source__6ff7bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["status", "created_at"], name="taxonomy_im_status_474fed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawcatalogueoflife",
            index=models.Index(
                fields=["import_job", "is_processed"], name="taxonomy_ra_import__35478e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawcatalogueoflife",
            index=models.Index(
                fields=["scientific_name", "status"], name="taxonomy_ra_scienti_8c6ea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawcatalogueoflife",
            index=models.Index(fields=["col_id"], name="taxonomy_ra_col_id_132a6b_idx"),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(
                fields=["scientific_name", "status"], name="taxonomy_ta_scienti_60664c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(
                fields=["genus", "specific_epithet", "status"], name="taxonomy_ta_genus_5e1f0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["environment"], name="taxonomy_ta_environ_91fabb_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(
                fields=["kingdom", "phylum", "class_name"], name="taxonomy_ta_kingdom_b46df5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(fields=["created_at"], name="taxonomy_ta_created_f6fa0a_idx"),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(fields=["updated_at"], name="taxonomy_ta_updated_959079_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="taxonomy",
            unique_together={("source", "source_taxon_id")},
        ),
        migrations.AddIndex(
            model_name="geographicdistribution",
            index=models.Index(
                fields=["taxonomy", "area_code"], name="taxonomy_ge_taxonom_43b71d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geographicdistribution",
            index=models.Index(
                fields=["establishment_means"], name="taxonomy_ge_establi_c659f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commonname",
            index=models.Index(fields=["name", "language"], name="taxonomy_co_name_1b3061_idx"),
        ),
        migrations.AddIndex(
            model_name="commonname",
            index=models.Index(
                fields=["taxonomy", "is_preferred"], name="taxonomy_co_taxonom_612f57_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commonname",
            unique_together={("taxonomy", "name", "language", "country")},
        ),
    ]
