# Generated by Django 5.2.8 on 2025-11-18 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("spelling correction", "Spelling Correction"),
                            ("basionym", "Basionym"),
                            ("based on", "Based On"),
                            ("replacement name", "Replacement Name"),
                            ("conserved", "Conserved"),
                            ("later homonym", "Later Homonym"),
                            ("superfluous", "Superfluous"),
                            ("homotypic synonym", "Homotypic Synonym"),
                            ("heterotypic synonym", "Heterotypic Synonym"),
                            ("proparte synonym", "Pro Parte Synonym"),
                            ("misapplied", "Misapplied"),
                            ("type", "Type"),
                        ],
                        db_index=True,
                        help_text="Type of relationship from COL NameRelation",
                        max_length=50,
                    ),
                ),
                ("col_name_id", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "col_related_name_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("col_source_id", models.CharField(blank=True, max_length=20)),
                ("reference_id", models.CharField(blank=True, max_length=50)),
                ("page", models.CharField(blank=True, max_length=50)),
                ("remarks", models.TextField(blank=True)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.importjob",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        help_text="Source name in the relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_relations_from",
                        to="taxonomy.taxonomy",
                    ),
                ),
                (
                    "related_name",
                    models.ForeignKey(
                        help_text="Target name in the relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_relations_to",
                        to="taxonomy.taxonomy",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="taxonomy.datasource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="namerelation",
            index=models.Index(fields=["name", "relation_type"], name="taxonomy_na_name_id_b3a2b8_idx"),
        ),
        migrations.AddIndex(
            model_name="namerelation",
            index=models.Index(
                fields=["related_name", "relation_type"], name="taxonomy_na_related_1aea1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="namerelation",
            index=models.Index(fields=["col_name_id"], name="taxonomy_na_col_nam_9ec58f_idx"),
        ),
        migrations.AddIndex(
            model_name="namerelation",
            index=models.Index(
                fields=["col_related_name_id"], name="taxonomy_na_col_rel_43bcfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="namerelation",
            index=models.Index(
                fields=["relation_type", "created_at"], name="taxonomy_na_relatio_bb3ce0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="namerelation",
            unique_together={("name", "related_name", "relation_type")},
        ),
    ]
