# Generated by Django 5.2.7 on 2025-10-20 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DexEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        help_text="Original uploaded image", upload_to="dex/original/%Y/%m/"
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True,
                        help_text="Processed/cropped image for card display",
                        null=True,
                        upload_to="dex/processed/%Y/%m/",
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude of capture location",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "location_lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude of capture location",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, help_text="Human-readable location name", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="User notes about this capture")),
                (
                    "customizations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Card styling: background, stickers, frames, etc.",
                    ),
                ),
                (
                    "catch_date",
                    models.DateTimeField(help_text="When the animal was observed/photographed"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("friends", "Friends Only"),
                            ("public", "Public"),
                        ],
                        default="friends",
                        help_text="Who can see this entry",
                        max_length=10,
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, help_text="User marked as favorite"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.ForeignKey(
                        help_text="The animal species",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dex_entries",
                        to="animals.animal",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who captured this animal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dex_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dex Entry",
                "verbose_name_plural": "Dex Entries",
                "db_table": "dex_entries",
                "ordering": ["-catch_date"],
                "indexes": [
                    models.Index(fields=["owner", "animal"], name="dex_entries_owner_i_ad7aa6_idx"),
                    models.Index(
                        fields=["owner", "catch_date"], name="dex_entries_owner_i_fe963b_idx"
                    ),
                    models.Index(
                        fields=["owner", "visibility"], name="dex_entries_owner_i_8f94d9_idx"
                    ),
                    models.Index(
                        fields=["animal", "visibility"], name="dex_entries_animal__157797_idx"
                    ),
                    models.Index(fields=["catch_date"], name="dex_entries_catch_d_ac62b8_idx"),
                    models.Index(fields=["is_favorite"], name="dex_entries_is_favo_2f836d_idx"),
                ],
                "unique_together": {("owner", "animal", "catch_date")},
            },
        ),
    ]
