# Generated by Django 5.2.8 on 2025-11-11 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_add_taxonomic_indexes"),
        ("dex", "0002_add_source_vision_job"),
        ("vision", "0002_add_dex_compatible_image_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dexentry",
            index=models.Index(fields=["owner", "updated_at"], name="dex_owner_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="dexentry",
            index=models.Index(
                fields=["visibility", "updated_at"], name="dex_visibility_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dexentry",
            index=models.Index(fields=["updated_at"], name="dex_updated_at_idx"),
        ),
    ]
