# Generated by Django 5.2.7 on 2025-10-20 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        help_text="Binomial nomenclature (Genus species)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "common_name",
                    models.CharField(help_text="Common name in English", max_length=200),
                ),
                ("kingdom", models.CharField(default="Animalia", max_length=100)),
                ("phylum", models.CharField(blank=True, max_length=100)),
                (
                    "class_name",
                    models.CharField(
                        blank=True, db_column="class", help_text="Taxonomic class", max_length=100
                    ),
                ),
                ("order", models.CharField(blank=True, max_length=100)),
                ("family", models.CharField(blank=True, max_length=100)),
                ("genus", models.CharField(blank=True, max_length=100)),
                ("species", models.CharField(blank=True, max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of the animal"),
                ),
                (
                    "habitat",
                    models.TextField(
                        blank=True, help_text="Natural habitat and geographic distribution"
                    ),
                ),
                ("diet", models.TextField(blank=True, help_text="Dietary habits")),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("EX", "Extinct"),
                            ("EW", "Extinct in the Wild"),
                            ("CR", "Critically Endangered"),
                            ("EN", "Endangered"),
                            ("VU", "Vulnerable"),
                            ("NT", "Near Threatened"),
                            ("LC", "Least Concern"),
                            ("DD", "Data Deficient"),
                            ("NE", "Not Evaluated"),
                        ],
                        default="NE",
                        help_text="IUCN Red List conservation status",
                        max_length=2,
                    ),
                ),
                (
                    "interesting_facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of interesting facts about the animal",
                    ),
                ),
                (
                    "creation_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Sequential discovery number (like Pokedex #)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Whether this record has been verified by admins"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="First user to discover this animal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_animals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal",
                "verbose_name_plural": "Animals",
                "db_table": "animals",
                "ordering": ["creation_index", "scientific_name"],
                "indexes": [
                    models.Index(fields=["scientific_name"], name="animals_scienti_17f063_idx"),
                    models.Index(fields=["common_name"], name="animals_common__399f2e_idx"),
                    models.Index(fields=["genus", "species"], name="animals_genus_43b545_idx"),
                    models.Index(fields=["creation_index"], name="animals_creatio_21a452_idx"),
                    models.Index(fields=["verified"], name="animals_verifie_e324b2_idx"),
                    models.Index(fields=["created_at"], name="animals_created_59ceee_idx"),
                ],
            },
        ),
    ]
