# Generated by Django 5.2.8 on 2025-11-06 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="establishment_means",
            field=models.CharField(
                blank=True, help_text="Native, introduced, invasive, etc.", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="last_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time taxonomy was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="native_regions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Native geographic regions",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="subfamily",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="animal",
            name="taxonomy_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Confidence score from taxonomy lookup",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="taxonomy_id",
            field=models.UUIDField(
                blank=True, db_index=True, help_text="Link to taxonomy.Taxonomy record", null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="taxonomy_source",
            field=models.CharField(
                blank=True, help_text='Source database (e.g., "col", "gbif")', max_length=20
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="taxonomy_source_url",
            field=models.URLField(blank=True, help_text="Direct link to source taxonomy record"),
        ),
        migrations.AddField(
            model_name="animal",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("taxonomy", "Taxonomy Database"),
                    ("cv", "Computer Vision"),
                    ("user", "User Submitted"),
                ],
                default="cv",
                help_text="How this animal was verified",
                max_length=30,
            ),
        ),
    ]
