# Generated by Django 5.2.8 on 2025-11-07 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_animal_establishment_means_animal_last_verified_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["kingdom", "phylum", "class_name"], name="animals_taxonomy_kpc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["family", "genus", "species"], name="animals_taxonomy_fgs_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["created_by"], name="animals_created_by_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["kingdom"], name="animals_kingdom_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["phylum"], name="animals_phylum_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["class_name"], name="animals_class_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["order"], name="animals_order_idx"),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["family"], name="animals_family_idx"),
        ),
    ]
