# Generated by Django 5.2.7 on 2025-11-05 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("vision_job", "Vision Analysis Job"),
                            ("user_upload", "Direct User Upload"),
                            ("dex_edit", "Dex Entry Edit"),
                        ],
                        help_text="Type of source that created this image",
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the source object (generic foreign key)",
                        null=True,
                    ),
                ),
                (
                    "original_file",
                    models.ImageField(
                        help_text="Original uploaded image file", upload_to="images/original/%Y/%m/"
                    ),
                ),
                (
                    "processed_file",
                    models.ImageField(
                        help_text="Processed image with transformations applied",
                        upload_to="images/processed/%Y/%m/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Optional thumbnail for list views",
                        null=True,
                        upload_to="images/thumbnails/%Y/%m/",
                    ),
                ),
                (
                    "original_format",
                    models.CharField(
                        help_text="Original file format (JPEG, PNG, etc.)", max_length=10
                    ),
                ),
                (
                    "original_dimensions",
                    models.JSONField(
                        help_text='Original dimensions as {"width": int, "height": int}'
                    ),
                ),
                (
                    "processed_dimensions",
                    models.JSONField(
                        help_text='Processed dimensions as {"width": int, "height": int}'
                    ),
                ),
                ("file_size_bytes", models.IntegerField(help_text="File size in bytes")),
                (
                    "transformations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Applied transformations: {"rotation": 90, "crop": {...}, "brightness": 1.1, etc.}',
                    ),
                ),
                (
                    "processing_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of warning messages during processing",
                    ),
                ),
                (
                    "processing_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of error messages during processing",
                    ),
                ),
                (
                    "exif_data",
                    models.JSONField(blank=True, default=dict, help_text="Extracted EXIF metadata"),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Version number of this image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_checksum",
                    models.CharField(
                        db_index=True, help_text="SHA256 checksum of original file", max_length=64
                    ),
                ),
                (
                    "processed_checksum",
                    models.CharField(
                        db_index=True, help_text="SHA256 checksum of processed file", max_length=64
                    ),
                ),
                (
                    "parent_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent image if this is a derived version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="images.processedimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed Image",
                "verbose_name_plural": "Processed Images",
                "db_table": "processed_images",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"], name="processed_i_source__1105ae_idx"
                    ),
                    models.Index(
                        fields=["original_checksum"], name="processed_i_origina_b03794_idx"
                    ),
                    models.Index(
                        fields=["processed_checksum"], name="processed_i_process_95edee_idx"
                    ),
                    models.Index(fields=["created_at"], name="processed_i_created_cd3b4a_idx"),
                ],
            },
        ),
    ]
