# Generated by Django 5.2.7 on 2025-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='image',
            field=models.ImageField(
                help_text='Original uploaded image',
                upload_to='vision/analysis/original/%Y/%m/'
            ),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='dex_compatible_image',
            field=models.ImageField(
                blank=True,
                help_text='Standardized PNG image for display (max 2560x2560)',
                null=True,
                upload_to='vision/analysis/dex_compatible/%Y/%m/'
            ),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='image_conversion_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('unnecessary', 'Unnecessary')
                ],
                default='pending',
                help_text='Status of image standardization',
                max_length=20
            ),
        ),
    ]
